### ISSUE TITLE
[BUG]: ./gradlew installDebug, open the App, it will crashed.

### ISSUE THREAD

**Issue by xuwanjin** [AndroidDev-social/MastodonCompose#83]
### Description of the bug

./gradlew installDebug, open the App, it will crashed.

### Steps To Reproduce

1. git clone https://github.com/AndroidDev-social/MastodonCompose.git
2.  ./gradlew installDebug, open the App, holder seconds in login screen, it will crash

### Additional Information
Android Version: Android 13
OS: Pixel experience
the crash log
2022-11-25 07:57:49.860 28704-28704/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: social.androiddev.mastodon, PID: 28704
    java.lang.NullPointerException: decodeByteArray(byteArray, 0, byteArray.size) must not be null
        at social.androiddev.common.utils.ImageLoadingKt.loadImageIntoPainter(ImageLoading.kt:21)
        at social.androiddev.common.utils.ImageLoadingKt$loadImageIntoPainter$1.invokeSuspend(Unknown Source:13)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@39a2b44, androidx.compose.runtime.BroadcastFrameClock@c6b542d, StandaloneCoroutine{Cancelling}@526bd62, AndroidUiDispatcher@afeaef3]
2022-11-25 07:57:49.864 1440-28746/? I/Dro

**Comment by crocsandcoffee** [comment]
@xuwanjin I cannot reproduce on latest `main`. Can you confirm the branch you built from and if you have latest?

**Comment by thebino** [comment]
I'm also not able to reproduce it. Regarding the stacktrace, it looks like the given url isnt' valid or hasn't had any response data.

**Comment by xuwanjin** [comment]
I reproduce it by close the data and wifi when I first open it. sorry. it's seems my wrong.

**Comment by crocsandcoffee** [comment]
Thanks, I was able to reproduce with airplane mode ON as well as turning off data/wifi. I fixed the issue here: https://github.com/AndroidDev-social/MastodonCompose/pull/84
